name: Deploy Preview
'on':
  - pull_request
jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Install Projects
        run: pnpm install
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get PR number
        id: get_pull_request_sha
        run: |
          pull_request_sha=$(jq --raw-output .pull_request.base.sha
          "$GITHUB_EVENT_PATH" | cut -c1-8)

          echo "pull_request_sha=${pull_request_sha}" >> $GITHUB_OUTPUT

          echo $pull_request_sha

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Build Project Artifacts
        run: |
         cd apps/nestjs
         vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN }}
         vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Preview to Vercel
        id: deploy
        run: |
         cd apps/nestjs
         echo preview_url=$(vercel deploy --token=${{secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT
    
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}