name: Deploy Preview
'on':
  - pull_request
jobs:
  test_filter:
    runs-on: ubuntu-latest
    outputs:
      has_modified: ${{ steps.filter.outputs.nextjs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            nextjs:
              - 'apps/nextjs/**'
  deploy-preview:
    runs-on: ubuntu-latest
    needs: test_filter
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Markdown
        if: ${{ needs.test_filter.outputs.has_modified == 'true' }}
        run: echo "FUNCIONOU CARALHOq"