name: Deploy Preview
'on':
  - pull_request
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Get PR number
        id: get_pull_request_sha
        run: |
          pull_request_sha=$(jq --raw-output .pull_request.base.sha
          "$GITHUB_EVENT_PATH" | cut -c1-8)

          echo "pull_request_sha=${pull_request_sha}" >> $GITHUB_OUTPUT

          echo $pull_request_sha
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: 'vercel build --token=${{ secrets.VERCEL_TOKEN }}'

      - name: Deploy Preview to Vercel
        id: deploy
        run: echo preview_url=$(vercel /apps/nestjs --prebuilt --token=${{secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT
    
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}